using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Block2Script : MonoBehaviour
{
    public float moveSpeed = 5;
    public float deadZone = -15;
    public BlockScript player;

    // Start is called before the first frame update
    void Start()
    {
        player = GameObject.FindGameObjectWithTag("Player").GetComponent<BlockScript>();
    }

    // Update is called once per frame
    void Update()
    {
        if (player.IsAlive) {
            transform.position = transform.position + (Vector3.left * moveSpeed) * Time.deltaTime;
        }

        if(transform.position.x<deadZone){
            Debug.Log("Block Deleted");
            Destroy(gameObject);
        }
    }

    void OnCollisionEnter2D(Collision2D collision) {
        if (collision.gameObject.layer==7) {
            Debug.Log("Block Destroyed cause of Overlapping!");
            Destroy(gameObject);      
        }
    }

}
